    public static function chineseSimplifiedTranslations(): array
    {
        // Note the special characters used in plural and context-sensitive translations.
        return [
            'Extended family' => '大家庭',
            'A tab showing the extended family of an individual.'=>'显示位人大家庭的选项卡。',
            'In which sequence should the parts of the extended family be shown?'=>'大家庭的各位部分应该按什么顺序显示？',
            'Family part'=>'家庭部分',
            'Show name of proband as short name or as full name?'=>'先证者的姓名是简称还是全名？',
            'Show options to filter the results (gender and alive/dead)?'=>'显示过滤结果的选项（性别和活/死）？',
            'Show filter options'=>'显示过滤器选项',
            'How should empty parts of extended family be presented?'=>'大家庭的空部分应该如何呈现？',
            'Show empty block'=>'显示空块',
            'yes, always at standard location'=>'是的，总是在标准地点',
            'no, but collect messages about empty blocks at the end'=>'没有，但是在最后收集关于空块的消息',
            'never'=>'从不',
            'The short name is based on the probands Rufname or nickname. If these are not available, the first of the given names is used, if one is given. Otherwise the last name is used.'=>'简称基于先证者的姓名或昵称。如果这些名称不可用，则使用给定名称中的第一位（如果给定）。否则将使用姓氏。',
            'Show short name'=>'显示短名称',
            'Show labels in special situations?'=>'在特殊情况下显示标签？',
            'Labels (or stickers) are used for example for adopted persons or foster children.'=>'标签（或贴纸）用于收养人或寄养儿童。',
            'Show labels'=>'显示标签',
            'Use the compact design?'=>'使用紧凑型设计？',
            'Use the compact design'=>'使用紧凑的设计',
            'The compact design only shows the name and life span for each person. The enriched design also shows a photo (if this is activated for this tree) as well as birth and death information.'=>'紧凑的设计只显示每位人的姓名和寿命。丰富的设计还显示了一张照片（如果这是为这棵树激活的）以及出生和死亡信息。',

            'don\t use this filter'=>'不要使用此筛选器',
            'show only male persons'=>'只显示男性',
            'show only female persons'=>'只显示女性',
            'show only persons of unknown gender'=>'只显示未知性别的人',
            'show only alive persons'=>'只显示活着的人',
            'show only dead persons'=>'只显示死人',
            'alive'=>'活着的',
            'dead'=>'死去的',
            'a dead person'=>'死人',
            'a living person'=>'活人',
            'not a male person'=>'不是男性',
            'not a female person'=>'不是女性',
            'not a person of unknown gender'=>'不是一位性别不明的人',

            'twin'=>'双胞胎',
            'triplet'=>'三胞胎',
            'quadruplet'=>'四胞胎',
            'quintuplet'=>'五胞胎',
            'sextuplet'=>'六胞胎',
            'septuplet'=>'七胞胎',
            'octuplet'=>'八胞胎',
            'nonuplet'=>'九胞胎',
            'decuplet'=>'十胞胎',
            'stillborn'=>'死胎',
            'died as infant'=>'在婴儿时期就去世了',
            'linkage challenged'=>'联系受到挑战',
            'linkage disproven'=>'连锁反证',
            'linkage proven'=>'链接已被证明',

            'Marriage'=>'婚内',
            'Ex-marriage'=>'前任',
            'Partnership'=>'婚姻关系',
            'Fiancée'=>'未婚妻',
            ' with '=>'：',
            'Biological parents of father'=>'父亲的亲生父母',
            'Biological parents of mother'=>'母亲的亲生父母',
            'Biological grandparents of father'=>'父亲的亲生祖父母',
            'Biological grandparents of mother'=>'母亲的亲生祖父母',
            'Biological parents of parent'=>'亲生父母',
            'Biological great-grandparents'=>'亲生曾祖父母',
            'Stepparents of father'=>'继父',
            'Stepparents of mother'=>'继母',
            'Stepparents of parent'=>'父母的继父母',
            'Parents of stepparent'=>'继父或继母的父母',
            'Siblings of father'=>'父亲的兄弟姐妹',
            'Siblings of mother'=>'母亲的兄弟姐妹',
            'Siblings-in-law of father'=>'父亲兄弟姐妹的配偶',
            'Siblings-in-law of mother'=>'母亲兄弟姐妹的配偶',
            'Biological parents'=>'亲生父母',
            'Stepparents'=>'继父母',
            'Parents-in-law of biological children'=>'亲生子女的岳父母\公婆',
            'Parents-in-law of stepchildren'=>'继子女的岳父母\公婆',
            'Full siblings'=>'兄弟姐妹',
            'Half siblings'=>'同父异母的兄弟姐妹',
            'Stepsiblings'=>'继兄弟姐妹',
            'Children of full siblings of father'=>'父亲的兄弟姐妹的子女',
            'Children of full siblings of mother'=>'母亲兄弟姐妹的子女',
            'Children of full siblings of parent'=>'父母的兄弟姐妹的子女',
            'Children of half siblings of father'=>'同父异母兄弟姐妹的子女',
            'Children of half siblings of mother'=>'母亲同父异母兄弟姐妹的子女',
            'Children of half siblings of parent'=>'同父异母兄弟姐妹的子女',
            'Siblings of partners'=>'配偶的兄弟姐妹',
            'Partners of siblings'=>'兄弟姐妹的配偶',
            'Siblings of siblings-in-law'=>'姐妹夫\姨子的兄弟姐妹',
            'Partners of siblings-in-law'=>'姊夫\叔子\姨子的配偶',
            'Children of siblings'=>'兄弟姐妹的子女',
            'Children of full siblings'=>'兄弟姐妹的子女',
            'Siblings\' stepchildren'=>'兄弟姐妹的继子女',
            'Children of siblings of partners'=>'配偶兄弟姐妹的子女',
            'Children of full siblings of biological parents' => '亲生父母的亲兄弟姐妹的子女',
            'Biological children'=>'亲生子女',
            'Stepchildren'=>'继子女',
            'Stepchild'=>'继子',
            'Stepson'=>'继子',
            'Stepdaughter'=>'继女',
            'Partners of biological children'=>'亲生子女的配偶',
            'Partners of biological grandchildren'=>'亲生孙辈的配偶',
            'Partners of stepchildren'=>'继子女的配偶',
            'Biological grandchildren'=>'亲生孙辈',
            'Stepchildren of children'=>'孩子的继子女',
            'Children of stepchildren'=>'继子女的子女',
            'Stepchildren of stepchildren'=>'继子女的继子女',
            'no blood relationship'=>'没有血缘关系',
            'relationship coefficient: %.1f'=>'血缘相关系数：%.1f',
            'generation +%s' => '辈份 +%s 辈 ',
            'generation %s' => '辈份 %s 辈 ',
            'same generation'=>'同辈人 ',

            'He'=>'他',
            'She'=>'她',
            'He/she'=>'他/她',
            'Mr.'=>'先生',
            'Mrs.'=>'夫人',
            'No family available'=>'没有家人',
            'Summary for the shown extended family'=>'所示大家庭的摘要',
            'The extended family of %1$s has one member.'. I18N::PLURAL .'The extended family of %1$s has %2$d members.'=>'%1$s的大家庭有%2$d位成员。',

            '%s has no %s recorded.'=>'%没有记录%s。',
            '%s has no %s, and no %s recorded.'=>'%s没有%s，也没有%s记录。',

            'Father\s family (%d)'=>'父亲的家庭（%d）',
            'Mother\s family (%d)'=>'母亲的家庭（%d）',
            'Father\s and Mother\'s family (%d)'=>'父亲和母亲的家庭（%d）',
            'Parents %1$s of %2$s'=>'家长%1$s（生%2$s）',
            'Parents %1$s (%2$s) of %3$s'=>'家长%1$s（%2$s）生%3$s',
            'Partners of %s'=>'%s配偶',
            'Brother %1$s of partner %2$s'=>'配偶%2$s的兄弟%1$s',
            'Sister %1$s of partner %2$s'=>'配偶%2$s的姐妹%1$s',
            'Sibling %1$s of partner %2$s'=>'配偶%2$s的兄弟%1$s',
            
            'Great-grandparents'  => '曾祖父辈',
            '%s has no great-grandparents recorded.'  => '%s没有曾祖父辈的记录。',
            '%s has one great-grandmother recorded.'  => '%s有一个曾祖母的记录。',
            '%s has one great-grandfather recorded.'  => '%s有一个曾祖父的记录。',
            '%s has one great-grandparent of unknown sex recorded.'  => '%s有一个曾祖辈的记录。',
            '%2$s has %1$d great-grandmother recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandmothers recorded.'  => '%s有%1$d个曾祖母的记录。',
            '%2$s has %1$d great-grandfather recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandfathers recorded.'  => '%s有%1$d个曾祖父的记录。',
            '%2$s has %1$d great-grandparent of unknown sex recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandparents of unknown sex recorded.'  => '%s有%1$d个曾祖父辈的记录。',
            '%2$s has %1$d great-grandfather and ' . I18N::PLURAL . '%2$s has %1$d great-grandfathers and '  => '%2$s记录有%1$d个曾祖父和',
            '%d great-grandmother recorded (%d in total).' . I18N::PLURAL . '%d great-grandmothers recorded (%d in total).'  => '%d个曾祖母 (共%d位).',
            '%2$s has %1$d great-grandmother and ' . I18N::PLURAL . '%2$s has %1$d great-grandmothers and '  => '%2$s有%1$d位曾祖母和',
            '%d great-grandparent of unknown sex recorded (%d in total).' . I18N::PLURAL . '%d great-grandparents of unknown sex recorded (%d in total).'  => '%d位曾祖辈 (共%d位)',
            '%2$s has %1$d great-grandfather,' . I18N::PLURAL . '%2$s has %1$d great-grandfathers,'  => '%2$s有%1$d位曾祖父',
            '%d great-grandmother, and ' . I18N::PLURAL . '%d great-grandmothers, and '  => '%d位曾祖母和',


            'Grandparents'=>'祖父辈',
            'Biological grandparents'=>'亲生祖父母',
            '%s has no grandparents recorded.'=>'%s没有祖父母的记录。',
            '%s has one grandmother recorded.'=>'%s有一位祖母的记录。',
            '%s has one grandfather recorded.'=>'%s有一位祖父的记录。',
            '%s has one grandparent recorded.'=>'%s有一位祖父母的记录。',
            '%2$s has %1$d grandmother recorded. '. I18N::PLURAL .'%2$s has %1$d grandmothers recorded.'=>'%2$s有%1$d位祖母',
            '%2$s has %1$d grandfather recorded. '. I18N::PLURAL .'%2$s has %1$d grandfathers recorded.'=>'%2$s有%1$d位祖父',
            '%2$s has %1$d grandfather and '. I18N::PLURAL .'%2$s has %1$d grandfathers and '=>'%2$s有%1$d位祖父和',
            '%d grandmother recorded (%d in total).'. I18N::PLURAL .'%d grandmothers recorded (%d in total).'=>'%d位祖母（共%d位）。',

            'Uncles and Aunts'=>'叔父舅父姑妈和姨妈',
            'Full siblings of biological parents'=>'亲生父母的兄弟姐妹',
            '%s has no uncles or aunts recorded.'=>'%s没有记录叔父舅父姑妈或姨妈。',
            '%s has one aunt recorded.'=>'%s有一位姑妈(姨妈)的记录。',
            '%s has one uncle recorded.'=>'%s有一位叔(舅)父的记录。',
            '%s has one uncle or aunt recorded.'=>'%s有一位叔(舅)父或姑妈(姨妈)的记录。',
            '%2$s has %1$d aunt recorded.'. I18N::PLURAL .'%2$s has %1$d aunts recorded.'=>'%2$s有%1$d姑妈(姨妈)。',
            '%2$s has %1$d uncle recorded.'. I18N::PLURAL .'%2$s has %1$d uncles recorded.'=>'%2$s有%1$d位叔(舅)父。',
            '%2$s has %1$d uncle and '. I18N::PLURAL .'%2$s has %1$d uncles and '=>'%2$s有%1$d位叔(舅)父和',
            '%d aunt recorded (%d in total).'. I18N::PLURAL .'%d aunts recorded (%d in total).'=>'%d位姑妈(姨妈)（共%d位）。',

            'Uncles and Aunts by marriage'=>'姑父、姨父、婶婶或舅娘',
            '%s has no uncles or aunts by marriage recorded.'=>'%s没有记录姑父、姨父、婶婶或舅娘。',
            '%s has one aunt by marriage recorded.'=>'%s有一位婶婶或舅娘记录。',
            '%s has one uncle by marriage recorded.'=>'%s有一位姑父或姨父记录。',
            '%s has one uncle or aunt by marriage recorded.'=>'%s有一位姑父、姨父、婶婶或舅娘。',
            '%2$s has %1$d aunt by marriage recorded.'. I18N::PLURAL .'%2$s has %1$d aunts by marriage recorded.'=>'%2$s有%1$d位婶婶(舅娘)',
            '%2$s has %1$d uncle by marriage recorded.'. I18N::PLURAL .'%2$s has %1$d uncles by marriage recorded.'=>'%2$s有%1$d位姑父(姨父)。',
            '%2$s has %1$d uncle by marriage and '. I18N::PLURAL .'%2$s has %1$d uncles by marriage and '=>'%2$s有%1$d位姑父(姨父)和',
            '%d aunt by marriage recorded (%d in total).'. I18N::PLURAL .'%d aunts by marriage recorded (%d in total).'=>'%d位婶婶(舅娘)（共%d位）。',


            'Parents'=>'父亲母亲',
            '%s has no parents recorded.'=>'%s没有父母的记录。',
            '%s has one mother recorded.'=>'%s有一位母亲的记录。',
            '%s has one father recorded.'=>'%s有一位父亲的记录。',
            '%s has one parent recorded.'=>'%s有单亲记录。',
            '%2$s has %1$d mother recorded.'. I18N::PLURAL .'%2$s has %1$d mothers recorded.'=>'%2$s有%1$d位母亲',
            '%2$s has %1$d father recorded.'. I18N::PLURAL .'%2$s has %1$d fathers recorded.'=>'%2$s有%1$d位父亲',
            '%2$s has %1$d father and '. I18N::PLURAL .'%2$s has %1$d fathers and '=>'%2$s有%1$d位父亲和',
            '%d mother recorded (%d in total).'. I18N::PLURAL .'%d mothers recorded (%d in total).'=>'%d名母亲的记录（共%d位）。',


            'Parents-in-law'=>'岳父母（公婆）',
            '%s has no parents-in-law recorded.'=>'%s没有岳父母（公婆）的记录。',
            '%s has one mother-in-law recorded.'=>'%s有一位岳母（婆婆）的记录。',
            '%s has one father-in-law recorded.'=>'%s有一位岳父（公公）的记录。',
            '%s has one parent-in-law recorded.'=>'%s有一位岳父母（公婆）。',
            '%2$s has %1$d mother-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d mothers-in-law recorded.'=>'%2$s有%1$d位岳母（婆婆）',
            '%2$s has %1$d father-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d fathers-in-law recorded.'=>'%2$s有%1$d位岳父（公公）',
            '%2$s has %1$d father-in-law and '. I18N::PLURAL .'%2$s has %1$d fathers-in-law and '=>'%2$s有%1$d位岳父（公公）和',
            '%d mother-in-law recorded (%d in total).'. I18N::PLURAL .'%d mothers-in-law recorded (%d in total).'=>'%d位岳母（婆婆）的记录（共%d位）。',


            'Co-parents-in-law'=>'儿女亲家',
            '%s has no co-parents-in-law recorded.'=>'%s没有儿女亲家记录。',
            '%s has one co-mother-in-law recorded.'=>'%s有一位亲家母的记录。',
            '%s has one co-father-in-law recorded.'=>'%s有一位亲家公的记录。',
            '%s has one co-parent-in-law recorded.'=>'%s有一位儿女亲家记录。',
            '%2$s has %1$d co-mother-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d co-mothers-in-law recorded.'=>'%2$s有%1$d位亲家母',
            '%2$s has %1$d co-father-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d co-fathers-in-law recorded.'=>'%2$s有%1$d位亲家公',
            '%2$s has %1$d co-father-in-law and '. I18N::PLURAL .'%2$s has %1$d co-fathers-in-law and '=>'%2$s有%1$d位亲家公和',
            '%d co-mother-in-law recorded (%d in total).'. I18N::PLURAL .'%d co-mothers-in-law recorded (%d in total).'=>'%d位亲家母（共%d）。',


            'Siblings'=>'兄弟姐妹',
            '%s has no siblings recorded.'=>'%s没有兄弟姐妹的记录。',
            '%s has one sister recorded.'=>'%s有一位姐妹的记录。',
            '%s has one brother recorded.'=>'%s有一位兄弟的记录。',
            '%s has one brother or sister recorded.'=>'%s有一个兄弟姐妹的记录。',
            '%2$s has %1$d sister recorded.'. I18N::PLURAL .'%2$s has %1$d sisters recorded.'=>'%2$s有%1$d位姐妹',
            '%2$s has %1$d brother recorded.'. I18N::PLURAL .'%2$s has %1$d brothers recorded.'=>'%2$s有%1$d位兄弟',
            '%2$s has %1$d brother and '. I18N::PLURAL .'%2$s has %1$d brothers and '=>'%2$s有%1$d位兄弟和',
            '%d sister recorded (%d in total).'. I18N::PLURAL .'%d sisters recorded (%d in total).'=>'%d位姐妹的记录（共%d位）',


            'Siblings-in-law'=>'姐(妹)夫\叔子\嫂子\弟媳\舅子\姨子',
            '%s has no siblings-in-law recorded.'=>'%s没有嫂子(姑姐妹\弟媳\姨子)。',
            '%s has one sister-in-law recorded.'=>'%s有一位嫂子(姑姐妹\弟媳\姨子)。',
            '%s has one brother-in-law recorded.'=>'%s有一位姐(妹)夫或舅子的记录。',
            '%s has one sibling-in-law recorded.'=>'%s有一个子妹配偶的记录。',
            '%2$s has %1$d sister-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d sisters-in-law recorded.'=>'%2$s有%1$d位嫂子(姑姐妹\弟媳\姨子)',
            '%2$s has %1$d brother-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d brothers-in-law recorded.'=>'%2$s有%1$d位姐夫(妹夫\叔子\舅子)',
            '%2$s has %1$d brother-in-law and '. I18N::PLURAL .'%2$s has %1$d brothers-in-law and '=>'%2$s有%1$d位姐夫(妹夫\叔子\舅子)和',
            '%d sister-in-law recorded (%d in total).'. I18N::PLURAL .'%d sisters-in-law recorded (%d in total).'=>'%d位嫂子(姑姐妹\弟媳\姨子)（共%d位）',

            'Co-siblings-in-law'=>'姻亲：舅母子\妯娌\连襟\姊夫',
            '%s has no co-siblings-in-law recorded.'=>'%s没有妯娌、连襟、姊夫记录。',
            '%s has one co-sister-in-law recorded.'=>'%s有一位舅母子\妯娌记录。',
            '%s has one co-brother-in-law recorded.'=>'%s有一位连襟\姊兄弟记录。',
            '%s has one co-sibling-in-law recorded.'=>'%s有一位舅母子\妯娌\连襟\姊夫记录。',
            '%2$s has %1$d co-sister-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d co-sisters-in-law recorded.'=>'%2$s有%1$d位舅母子\妯娌',
            '%2$s has %1$d co-brother-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d co-brothers-in-law recorded.'=>'%2$s有%1$d位连襟\姊夫',
            '%2$s has %1$d co-brother-in-law and '. I18N::PLURAL .'%2$s has %1$d co-brothers-in-law and '=>'%2$s有%1$d位连襟\姊夫和',
            '%d co-sister-in-law recorded (%d in total).'. I18N::PLURAL .'%d co-sisters-in-law recorded (%d in total).'=>'%d名舅母子\妯娌（共%d位）',


            'Partners'=>'配偶',
            'Partner of '=>'配偶：',
            '%s has no partners recorded.'=>'%s没有配偶的记录。',
            '%s has one female partner recorded.'=>'%s有一位妻子。',
            '%s has one male partner recorded.'=>'%s有一名丈夫。',
            '%s has one partner recorded.'=>'%s有一位配偶。',
            '%2$s has %1$d female partner recorded.'. I18N::PLURAL .'%2$s has %1$d female partners recorded.'=>'%2$s有%1$d位配偶',
            '%2$s has %1$d male partner recorded.'. I18N::PLURAL .'%2$s has %1$d male partners recorded.'=>'%2$s有%1$d位配偶',
            '%2$s has %1$d male partner and '. I18N::PLURAL .'%2$s has %1$d male partners and '=>'%2$s有%1$d名丈夫和',
            '%2$s has %1$d female partner and '. I18N::PLURAL .'%2$s has %1$d female partners and '=>'%2$s有%1$d名妻子和',
            '%d female partner recorded (%d in total).'. I18N::PLURAL .'%d female partners recorded (%d in total).'=>'%d位配偶（共%d位）',
            '%d male partner recorded (%d in total).'. I18N::PLURAL .'%d male partners recorded (%d in total).'=>'%d位配偶（共%d位）',
            '%d male partner of female partners recorded (%d in total).' . I18N::PLURAL . '%d male partners of female partners recorded (%d in total).'=> '%d位妻子的配偶(共%d位)',
            '%d female partner of male partners recorded (%d in total).' . I18N::PLURAL . '%d female partners of male partners recorded (%d in total).'=> '%d位丈夫的配偶(共%d位)',


            'Partner chains'=>'配偶系列',
            '%s has no members of a partner chain recorded.'=>'%s没有记录配偶链的成员。',
            'There are %d branches in the partner chain. '=>'配偶链中有%d位分支。',
            'The longest branch in the partner chain to %2$s consists of %1$d partners (including %3$s).'=>'%2$s配偶链中最长的分支由%1$d位配偶（包括%3$s）组成。',
            'The longest branch in the partner chain consists of %1$d partners (including %2$s).'=>'配偶链中最长的分支由%1$d位配偶（包括%2$s）组成。',
            '%d female partner in this partner chain recorded (%d in total). '. I18N::PLURAL .'%d female partners in this partner chain recorded (%d in total).'=>'%此配偶链中有d名女性配偶（%d总计）',

            'Cousins'=>'堂表亲',
            '%s has no first cousins recorded.'=>'%s没有表亲记录',
            '%s has one female first cousin recorded.'=>'%s有一位堂表姐妹的记录。',
            '%s has one male first cousin recorded.'=>'%s有一位堂表兄弟的记录。',
            '%s has one first cousin recorded.'=>'%s有一位堂表亲的记录。',
            '%2$s has %1$d female first cousin recorded.'. I18N::PLURAL .'%2$s has %1$d female first cousins recorded.'=>'%2$s有%1$d位堂表姐妹。',
            '%2$s has %1$d male first cousin recorded.'. I18N::PLURAL .'%2$s has %1$d male first cousins recorded.'=>'%2$s有%1$d位堂表兄弟',
            '%2$s has %1$d male first cousin and '. I18N::PLURAL .'%2$s has %1$d male first cousins and '=>'%2$s有%1$d位堂表兄弟和',
            '%d female first cousin recorded (%d in total).'. I18N::PLURAL .'%d female first cousins recorded (%d in total).'=>'%d位堂表姐妹（共%d位）。',


            'Nephews and Nieces'=>'侄子和侄女',
            '%s has no nephews or nieces recorded.'=>'%s没有侄子或侄女的记录。',
            '%s has one niece recorded.'=>'%s有一位侄女的记录。',
            '%s has one nephew recorded.'=>'%s有一位侄子的记录。',
            '%s has one nephew or niece recorded.'=>'%s有一位侄子或侄女的记录。',
            '%2$s has %1$d niece recorded. '. I18N::PLURAL .'%2$s has %1$d nieces recorded.'=>'%2$s有%1$d位侄女',
            '%2$s has %1$d nephew recorded. '. I18N::PLURAL .'%2$s has %1$d nephews recorded.'=>'%2$s有%1$d位侄子',
            '%2$s has %1$d nephew and '. I18N::PLURAL .'%2$s has %1$d nephews and '=>'%2$s有%1$d位侄子和',
            '%d niece recorded (%d in total).'. I18N::PLURAL .'%d nieces recorded (%d in total).'=>'%d位侄女记录（共%d位）',


            'Children'=>'子女',
            '%s has no children recorded.'=>'%s没有子女的记录。',
            '%s has one daughter recorded.'=>'%s有一个女儿。',
            '%s has one son recorded.'=>'%s有一个儿子的记录。',
            '%s has one child recorded.'=>'%s有一个子女。',
            '%2$s has %1$d daughter recorded.'. I18N::PLURAL .'%2$s has %1$d daughters recorded.'=>'%2$s有%1$d个女儿',
            '%2$s has %1$d son recorded.'. I18N::PLURAL .'%2$s has %1$d sons recorded.'=>'%2$s有%1$d个儿子',
            '%2$s has %1$d son and '. I18N::PLURAL .'%2$s has %1$d sons and '=>'%2$s有%1$d个儿子和',
            '%d daughter recorded (%d in total).'. I18N::PLURAL .'%d daughters recorded (%d in total).'=>'%d个女儿（共%d位）。',


            'Children-in-law'=>'儿媳和女婿',
            '%s has no children-in-law recorded.'=>'%s没有儿媳和女婿记录。',
            '%s has one daughter-in-law recorded.'=>'%s有一个儿媳的记录。',
            '%s has one son-in-law recorded.'=>'%s有一个女婿的记录。',
            '%s has one child-in-law recorded.'=>'%s有一个儿媳或女婿的记录。',
            '%2$s has %1$d daughter-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d daughters-in-law recorded.'=>'%2$s有%1$d位儿媳',
            '%2$s has %1$d son-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d sons-in-law recorded.'=>'%2$s有%1$d位女婿记录',
            '%2$s has %1$d son-in-law and '. I18N::PLURAL .'%2$s has %1$d sons-in-law and '=>'%2$s有%1$d位女婿和',
            '%d daughter-in-law recorded (%d in total).'. I18N::PLURAL .'%d daughters-in-law recorded (%d in total).'=>'%d位儿媳（共%d位）。',


            'Grandchildren'=>'孙辈',
            '%s has no grandchildren recorded.'=>'%s没有孙辈的记录。',
            '%s has one granddaughter recorded.'=>'%s有一个孙女。',
            '%s has one grandson recorded.'=>'%s有一个孙子。',
            '%s has one grandchild recorded.'=>'%s有一位孙辈的记录。',
            '%2$s has %1$d granddaughter recorded.'. I18N::PLURAL .'%2$s has %1$d granddaughters recorded.'=>'%2$s有%1$d位孙女',
            '%2$s has %1$d grandson recorded.'. I18N::PLURAL .'%2$s has %1$d grandsons recorded.'=>'%2$s有%1$d位孙子',
            '%2$s has %1$d grandson and '. I18N::PLURAL .'%2$s has %1$d grandsons and '=>'%2$s有%1$d位孙子和',
            '%d granddaughter recorded (%d in total).'. I18N::PLURAL .'%d granddaughters recorded (%d in total).'=>'%d位孙女记录（共%d位）',
            
            
            'Grandchildren-in-law' => '孙媳妇和孙女婿',
            '%s has no grandchildren-in-law recorded.' => '%s没有孙媳妇和孙女婿的记录。',
            '%s has one granddaughter-in-law recorded.' => '%s有一位孙媳妇',
            '%s has one grandson-in-law recorded.' => '%s有一位孙女婿',
            '%s has one grandchild-in-law of unknown sex recorded.' => '%s有一位孙辈的配偶',
            '%2$s has %1$d granddaughter-in-law recorded.' . I18N::PLURAL . '%2$s has %1$d granddaughters-in-law recorded.'
                => '%2$s有%1$d位孙媳妇',
            '%2$s has %1$d grandson-in-law recorded.' . I18N::PLURAL . '%2$s has %1$d grandsons-in-law recorded.'
                => '%2$s有%1$d位孙女婿',
            '%2$s has %1$d grandchild-in-law of unknown sex recorded.' . I18N::PLURAL . '%2$s has %1$d grandchildren-in-law of unknown sex recorded.'
                => '%s有%1$d位孙辈的配偶',
            '%2$s has %1$d grandson-in-law and ' . I18N::PLURAL . '%2$s has %1$d grandsons-in-law and '
                => '%2$s有%1$d位孙女婿和',
            '%d granddaughter-in-law recorded (%d in total).' . I18N::PLURAL . '%d granddaughters-in-law recorded (%d in total).'
                => '%d位孙媳妇（共%d位）',
            '%2$s has %1$d granddaughter-in-law and ' . I18N::PLURAL . '%2$s has %1$d granddaughters-in-law and '
                => '%2$s有%1$d位孙媳妇和',
            '%d grandchild-in-law of unknown sex recorded (%d in total).' . I18N::PLURAL . '%d grandchildren-in-law of unknown sex recorded (%d in total).'
                => '%d位孙辈的配偶（共%d位）。',
        ];
    }
    
    /**
     * tbd
     *
     * @return array
     */
    public static function chineseTraditionalTranslations(): array
    {
        // Note the special characters used in plural and context-sensitive translations.
        return [
            'Extended family' => '大家庭',
            'A tab showing the extended family of an individual.'=>'顯示位人大家庭的選項卡。',
            'In which sequence should the parts of the extended family be shown?'=>'大家庭的各位部分應該按什麽順序顯示？',
            'Family part'=>'家庭部分',
            'Show name of proband as short name or as full name?'=>'先證者的姓名是簡稱還是全名？',
            'Show options to filter the results (gender and alive/dead)?'=>'顯示過濾結果的選項（性別和活/死）？',
            'Show filter options'=>'顯示過濾器選項',
            'How should empty parts of extended family be presented?'=>'大家庭的空部分應該如何呈現？',
            'Show empty block'=>'顯示空塊',
            'yes, always at standard location'=>'是的，總是在標準地點',
            'no, but collect messages about empty blocks at the end'=>'沒有，但是在最後收集關於空塊的消息',
            'never'=>'從不',
            'The short name is based on the probands Rufname or nickname. If these are not available, the first of the given names is used, if one is given. Otherwise the last name is used.'=>'簡稱基於先證者的姓名或昵稱。如果這些名稱不可用，則使用給定名稱中的第一位（如果給定）。否則將使用姓氏。',
            'Show short name'=>'顯示短名稱',
            'Show labels in special situations?'=>'在特殊情況下顯示標簽？',
            'Labels (or stickers) are used for example for adopted persons or foster children.'=>'標簽（或貼紙）用於收養人或寄養兒童。',
            'Show labels'=>'顯示標簽',
            'Use the compact design?'=>'使用緊湊型設計？',
            'Use the compact design'=>'使用緊湊的設計',
            'The compact design only shows the name and life span for each person. The enriched design also shows a photo (if this is activated for this tree) as well as birth and death information.'=>'緊湊的設計只顯示每位人的姓名和壽命。豐富的設計還顯示了一張照片（如果這是為這棵樹激活的）以及出生和死亡信息。',

            'don\t use this filter'=>'不要使用此篩選器',
            'show only male persons'=>'只顯示男性',
            'show only female persons'=>'只顯示女性',
            'show only persons of unknown gender'=>'只顯示未知性別的人',
            'show only alive persons'=>'只顯示活著的人',
            'show only dead persons'=>'只顯示死人',
            'alive'=>'活著的',
            'dead'=>'死去的',
            'a dead person'=>'死人',
            'a living person'=>'活人',
            'not a male person'=>'不是男性',
            'not a female person'=>'不是女性',
            'not a person of unknown gender'=>'不是一位性別不明的人',

            'twin'=>'雙胞胎',
            'triplet'=>'三胞胎',
            'quadruplet'=>'四胞胎',
            'quintuplet'=>'五胞胎',
            'sextuplet'=>'六胞胎',
            'septuplet'=>'七胞胎',
            'octuplet'=>'八胞胎',
            'nonuplet'=>'九胞胎',
            'decuplet'=>'十胞胎',
            'stillborn'=>'死胎',
            'died as infant'=>'在嬰兒時期就去世了',
            'linkage challenged'=>'聯系受到挑戰',
            'linkage disproven'=>'連鎖反證',
            'linkage proven'=>'鏈接已被證明',

            'Marriage'=>'婚內',
            'Ex-marriage'=>'前任',
            'Partnership'=>'婚姻關系',
            'Fiancée'=>'未婚妻',
            ' with '=>'：',
            'Biological parents of father'=>'父親的親生父母',
            'Biological parents of mother'=>'母親的親生父母',
            'Biological grandparents of father'=>'父親的親生祖父母',
            'Biological grandparents of mother'=>'母親的親生祖父母',
            'Biological parents of parent'=>'親生父母',
            'Biological great-grandparents'=>'親生曾祖父母',
            'Stepparents of father'=>'繼父',
            'Stepparents of mother'=>'繼母',
            'Stepparents of parent'=>'父母的繼父母',
            'Parents of stepparent'=>'繼父或繼母的父母',
            'Siblings of father'=>'父親的兄弟姐妹',
            'Siblings of mother'=>'母親的兄弟姐妹',
            'Siblings-in-law of father'=>'父親兄弟姐妹的配偶',
            'Siblings-in-law of mother'=>'母親兄弟姐妹的配偶',
            'Biological parents'=>'親生父母',
            'Stepparents'=>'繼父母',
            'Parents-in-law of biological children'=>'親生子女的嶽父母\公婆',
            'Parents-in-law of stepchildren'=>'繼子女的嶽父母\公婆',
            'Full siblings'=>'兄弟姐妹',
            'Half siblings'=>'同父異母的兄弟姐妹',
            'Stepsiblings'=>'繼兄弟姐妹',
            'Children of full siblings of father'=>'父親的兄弟姐妹的子女',
            'Children of full siblings of mother'=>'母親兄弟姐妹的子女',
            'Children of full siblings of parent'=>'父母的兄弟姐妹的子女',
            'Children of half siblings of father'=>'同父異母兄弟姐妹的子女',
            'Children of half siblings of mother'=>'母親同父異母兄弟姐妹的子女',
            'Children of half siblings of parent'=>'同父異母兄弟姐妹的子女',
            'Siblings of partners'=>'配偶的兄弟姐妹',
            'Partners of siblings'=>'兄弟姐妹的配偶',
            'Siblings of siblings-in-law'=>'姐妹夫\姨子的兄弟姐妹',
            'Partners of siblings-in-law'=>'姊夫\叔子\姨子的配偶',
            'Children of siblings'=>'兄弟姐妹的子女',
            'Children of full siblings'=>'兄弟姐妹的子女',
            'Siblings\' stepchildren'=>'兄弟姐妹的繼子女',
            'Children of siblings of partners'=>'配偶兄弟姐妹的子女',
            'Children of full siblings of biological parents' => '親生父母的親兄弟姐妹的子女',
            'Biological children'=>'親生子女',
            'Stepchildren'=>'繼子女',
            'Stepchild'=>'繼子',
            'Stepson'=>'繼子',
            'Stepdaughter'=>'繼女',
            'Partners of biological children'=>'親生子女的配偶',
            'Partners of biological grandchildren'=>'親生孫輩的配偶',
            'Partners of stepchildren'=>'繼子女的配偶',
            'Biological grandchildren'=>'親生孫輩',
            'Stepchildren of children'=>'孩子的繼子女',
            'Children of stepchildren'=>'繼子女的子女',
            'Stepchildren of stepchildren'=>'繼子女的繼子女',
            'no blood relationship'=>'沒有血緣關系',
            'relationship coefficient: %.1f'=>'血緣相關系數：%.1f',
            'generation +%s' => '輩份 +%s 輩 ',
            'generation %s' => '輩份 %s 輩 ',
            'same generation'=>'同輩人 ',

            'He'=>'他',
            'She'=>'她',
            'He/she'=>'他/她',
            'Mr.'=>'先生',
            'Mrs.'=>'夫人',
            'No family available'=>'沒有家人',
            'Summary for the shown extended family'=>'所示大家庭的摘要',
            'The extended family of %1$s has one member.'. I18N::PLURAL .'The extended family of %1$s has %2$d members.'=>'%1$s的大家庭有%2$d位成員。',

            '%s has no %s recorded.'=>'%沒有記錄%s。',
            '%s has no %s, and no %s recorded.'=>'%s沒有%s，也沒有%s記錄。',

            'Father\s family (%d)'=>'父親的家庭（%d）',
            'Mother\s family (%d)'=>'母親的家庭（%d）',
            'Father\s and Mother\'s family (%d)'=>'父親和母親的家庭（%d）',
            'Parents %1$s of %2$s'=>'家長%1$s（生%2$s）',
            'Parents %1$s (%2$s) of %3$s'=>'家長%1$s（%2$s）生%3$s',
            'Partners of %s'=>'%s配偶',
            'Brother %1$s of partner %2$s'=>'配偶%2$s的兄弟%1$s',
            'Sister %1$s of partner %2$s'=>'配偶%2$s的姐妹%1$s',
            'Sibling %1$s of partner %2$s'=>'配偶%2$s的兄弟%1$s',
            
            'Great-grandparents'  => '曾祖父輩',
            '%s has no great-grandparents recorded.'  => '%s沒有曾祖父輩的記錄。',
            '%s has one great-grandmother recorded.'  => '%s有一個曾祖母的記錄。',
            '%s has one great-grandfather recorded.'  => '%s有一個曾祖父的記錄。',
            '%s has one great-grandparent of unknown sex recorded.'  => '%s有一個曾祖輩的記錄。',
            '%2$s has %1$d great-grandmother recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandmothers recorded.'  => '%s有%1$d個曾祖母的記錄。',
            '%2$s has %1$d great-grandfather recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandfathers recorded.'  => '%s有%1$d個曾祖父的記錄。',
            '%2$s has %1$d great-grandparent of unknown sex recorded.' . I18N::PLURAL . '%2$s has %1$d great-grandparents of unknown sex recorded.'  => '%s有%1$d個曾祖父輩的記錄。',
            '%2$s has %1$d great-grandfather and ' . I18N::PLURAL . '%2$s has %1$d great-grandfathers and '  => '%2$s記錄有%1$d個曾祖父和',
            '%d great-grandmother recorded (%d in total).' . I18N::PLURAL . '%d great-grandmothers recorded (%d in total).'  => '%d個曾祖母 (共%d位).',
            '%2$s has %1$d great-grandmother and ' . I18N::PLURAL . '%2$s has %1$d great-grandmothers and '  => '%2$s有%1$d位曾祖母和',
            '%d great-grandparent of unknown sex recorded (%d in total).' . I18N::PLURAL . '%d great-grandparents of unknown sex recorded (%d in total).'  => '%d位曾祖輩 (共%d位)',
            '%2$s has %1$d great-grandfather,' . I18N::PLURAL . '%2$s has %1$d great-grandfathers,'  => '%2$s有%1$d位曾祖父',
            '%d great-grandmother, and ' . I18N::PLURAL . '%d great-grandmothers, and '  => '%d位曾祖母和',


            'Grandparents'=>'祖父輩',
            'Biological grandparents'=>'親生祖父母',
            '%s has no grandparents recorded.'=>'%s沒有祖父母的記錄。',
            '%s has one grandmother recorded.'=>'%s有一位祖母的記錄。',
            '%s has one grandfather recorded.'=>'%s有一位祖父的記錄。',
            '%s has one grandparent recorded.'=>'%s有一位祖父母的記錄。',
            '%2$s has %1$d grandmother recorded. '. I18N::PLURAL .'%2$s has %1$d grandmothers recorded.'=>'%2$s有%1$d位祖母',
            '%2$s has %1$d grandfather recorded. '. I18N::PLURAL .'%2$s has %1$d grandfathers recorded.'=>'%2$s有%1$d位祖父',
            '%2$s has %1$d grandfather and '. I18N::PLURAL .'%2$s has %1$d grandfathers and '=>'%2$s有%1$d位祖父和',
            '%d grandmother recorded (%d in total).'. I18N::PLURAL .'%d grandmothers recorded (%d in total).'=>'%d位祖母（共%d位）。',

            'Uncles and Aunts'=>'叔父舅父姑媽和姨媽',
            'Full siblings of biological parents'=>'親生父母的兄弟姐妹',
            '%s has no uncles or aunts recorded.'=>'%s沒有記錄叔父舅父姑媽或姨媽。',
            '%s has one aunt recorded.'=>'%s有一位姑媽(姨媽)的記錄。',
            '%s has one uncle recorded.'=>'%s有一位叔(舅)父的記錄。',
            '%s has one uncle or aunt recorded.'=>'%s有一位叔(舅)父或姑媽(姨媽)的記錄。',
            '%2$s has %1$d aunt recorded.'. I18N::PLURAL .'%2$s has %1$d aunts recorded.'=>'%2$s有%1$d姑媽(姨媽)。',
            '%2$s has %1$d uncle recorded.'. I18N::PLURAL .'%2$s has %1$d uncles recorded.'=>'%2$s有%1$d位叔(舅)父。',
            '%2$s has %1$d uncle and '. I18N::PLURAL .'%2$s has %1$d uncles and '=>'%2$s有%1$d位叔(舅)父和',
            '%d aunt recorded (%d in total).'. I18N::PLURAL .'%d aunts recorded (%d in total).'=>'%d位姑媽(姨媽)（共%d位）。',

            'Uncles and Aunts by marriage'=>'姑父、姨父、嬸嬸或舅娘',
            '%s has no uncles or aunts by marriage recorded.'=>'%s沒有記錄姑父、姨父、嬸嬸或舅娘。',
            '%s has one aunt by marriage recorded.'=>'%s有一位嬸嬸或舅娘記錄。',
            '%s has one uncle by marriage recorded.'=>'%s有一位姑父或姨父記錄。',
            '%s has one uncle or aunt by marriage recorded.'=>'%s有一位姑父、姨父、嬸嬸或舅娘。',
            '%2$s has %1$d aunt by marriage recorded.'. I18N::PLURAL .'%2$s has %1$d aunts by marriage recorded.'=>'%2$s有%1$d位嬸嬸(舅娘)',
            '%2$s has %1$d uncle by marriage recorded.'. I18N::PLURAL .'%2$s has %1$d uncles by marriage recorded.'=>'%2$s有%1$d位姑父(姨父)。',
            '%2$s has %1$d uncle by marriage and '. I18N::PLURAL .'%2$s has %1$d uncles by marriage and '=>'%2$s有%1$d位姑父(姨父)和',
            '%d aunt by marriage recorded (%d in total).'. I18N::PLURAL .'%d aunts by marriage recorded (%d in total).'=>'%d位嬸嬸(舅娘)（共%d位）。',


            'Parents'=>'父親母親',
            '%s has no parents recorded.'=>'%s沒有父母的記錄。',
            '%s has one mother recorded.'=>'%s有一位母親的記錄。',
            '%s has one father recorded.'=>'%s有一位父親的記錄。',
            '%s has one parent recorded.'=>'%s有單親記錄。',
            '%2$s has %1$d mother recorded.'. I18N::PLURAL .'%2$s has %1$d mothers recorded.'=>'%2$s有%1$d位母親',
            '%2$s has %1$d father recorded.'. I18N::PLURAL .'%2$s has %1$d fathers recorded.'=>'%2$s有%1$d位父親',
            '%2$s has %1$d father and '. I18N::PLURAL .'%2$s has %1$d fathers and '=>'%2$s有%1$d位父親和',
            '%d mother recorded (%d in total).'. I18N::PLURAL .'%d mothers recorded (%d in total).'=>'%d名母親的記錄（共%d位）。',


            'Parents-in-law'=>'嶽父母（公婆）',
            '%s has no parents-in-law recorded.'=>'%s沒有嶽父母（公婆）的記錄。',
            '%s has one mother-in-law recorded.'=>'%s有一位嶽母（婆婆）的記錄。',
            '%s has one father-in-law recorded.'=>'%s有一位嶽父（公公）的記錄。',
            '%s has one parent-in-law recorded.'=>'%s有一位嶽父母（公婆）。',
            '%2$s has %1$d mother-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d mothers-in-law recorded.'=>'%2$s有%1$d位嶽母（婆婆）',
            '%2$s has %1$d father-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d fathers-in-law recorded.'=>'%2$s有%1$d位嶽父（公公）',
            '%2$s has %1$d father-in-law and '. I18N::PLURAL .'%2$s has %1$d fathers-in-law and '=>'%2$s有%1$d位嶽父（公公）和',
            '%d mother-in-law recorded (%d in total).'. I18N::PLURAL .'%d mothers-in-law recorded (%d in total).'=>'%d位嶽母（婆婆）的記錄（共%d位）。',


            'Co-parents-in-law'=>'兒女親家',
            '%s has no co-parents-in-law recorded.'=>'%s沒有兒女親家記錄。',
            '%s has one co-mother-in-law recorded.'=>'%s有一位親家母的記錄。',
            '%s has one co-father-in-law recorded.'=>'%s有一位親家公的記錄。',
            '%s has one co-parent-in-law recorded.'=>'%s有一位兒女親家記錄。',
            '%2$s has %1$d co-mother-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d co-mothers-in-law recorded.'=>'%2$s有%1$d位親家母',
            '%2$s has %1$d co-father-in-law recorded. '. I18N::PLURAL .'%2$s has %1$d co-fathers-in-law recorded.'=>'%2$s有%1$d位親家公',
            '%2$s has %1$d co-father-in-law and '. I18N::PLURAL .'%2$s has %1$d co-fathers-in-law and '=>'%2$s有%1$d位親家公和',
            '%d co-mother-in-law recorded (%d in total).'. I18N::PLURAL .'%d co-mothers-in-law recorded (%d in total).'=>'%d位親家母（共%d）。',


            'Siblings'=>'兄弟姐妹',
            '%s has no siblings recorded.'=>'%s沒有兄弟姐妹的記錄。',
            '%s has one sister recorded.'=>'%s有一位姐妹的記錄。',
            '%s has one brother recorded.'=>'%s有一位兄弟的記錄。',
            '%s has one brother or sister recorded.'=>'%s有一個兄弟姐妹的記錄。',
            '%2$s has %1$d sister recorded.'. I18N::PLURAL .'%2$s has %1$d sisters recorded.'=>'%2$s有%1$d位姐妹',
            '%2$s has %1$d brother recorded.'. I18N::PLURAL .'%2$s has %1$d brothers recorded.'=>'%2$s有%1$d位兄弟',
            '%2$s has %1$d brother and '. I18N::PLURAL .'%2$s has %1$d brothers and '=>'%2$s有%1$d位兄弟和',
            '%d sister recorded (%d in total).'. I18N::PLURAL .'%d sisters recorded (%d in total).'=>'%d位姐妹的記錄（共%d位）',


            'Siblings-in-law'=>'姐(妹)夫\叔子\嫂子\弟媳\舅子\姨子',
            '%s has no siblings-in-law recorded.'=>'%s沒有嫂子(姑姐妹\弟媳\姨子)。',
            '%s has one sister-in-law recorded.'=>'%s有一位嫂子(姑姐妹\弟媳\姨子)。',
            '%s has one brother-in-law recorded.'=>'%s有一位姐(妹)夫或舅子的記錄。',
            '%s has one sibling-in-law recorded.'=>'%s有一個子妹配偶的記錄。',
            '%2$s has %1$d sister-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d sisters-in-law recorded.'=>'%2$s有%1$d位嫂子(姑姐妹\弟媳\姨子)',
            '%2$s has %1$d brother-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d brothers-in-law recorded.'=>'%2$s有%1$d位姐夫(妹夫\叔子\舅子)',
            '%2$s has %1$d brother-in-law and '. I18N::PLURAL .'%2$s has %1$d brothers-in-law and '=>'%2$s有%1$d位姐夫(妹夫\叔子\舅子)和',
            '%d sister-in-law recorded (%d in total).'. I18N::PLURAL .'%d sisters-in-law recorded (%d in total).'=>'%d位嫂子(姑姐妹\弟媳\姨子)（共%d位）',

            'Co-siblings-in-law'=>'姻親：舅母子\妯娌\連襟\姊夫',
            '%s has no co-siblings-in-law recorded.'=>'%s沒有妯娌、連襟、姊夫記錄。',
            '%s has one co-sister-in-law recorded.'=>'%s有一位舅母子\妯娌記錄。',
            '%s has one co-brother-in-law recorded.'=>'%s有一位連襟\姊兄弟記錄。',
            '%s has one co-sibling-in-law recorded.'=>'%s有一位舅母子\妯娌\連襟\姊夫記錄。',
            '%2$s has %1$d co-sister-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d co-sisters-in-law recorded.'=>'%2$s有%1$d位舅母子\妯娌',
            '%2$s has %1$d co-brother-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d co-brothers-in-law recorded.'=>'%2$s有%1$d位連襟\姊夫',
            '%2$s has %1$d co-brother-in-law and '. I18N::PLURAL .'%2$s has %1$d co-brothers-in-law and '=>'%2$s有%1$d位連襟\姊夫和',
            '%d co-sister-in-law recorded (%d in total).'. I18N::PLURAL .'%d co-sisters-in-law recorded (%d in total).'=>'%d名舅母子\妯娌（共%d位）',


            'Partners'=>'配偶',
            'Partner of '=>'配偶：',
            '%s has no partners recorded.'=>'%s沒有配偶的記錄。',
            '%s has one female partner recorded.'=>'%s有一位妻子。',
            '%s has one male partner recorded.'=>'%s有一名丈夫。',
            '%s has one partner recorded.'=>'%s有一位配偶。',
            '%2$s has %1$d female partner recorded.'. I18N::PLURAL .'%2$s has %1$d female partners recorded.'=>'%2$s有%1$d位配偶',
            '%2$s has %1$d male partner recorded.'. I18N::PLURAL .'%2$s has %1$d male partners recorded.'=>'%2$s有%1$d位配偶',
            '%2$s has %1$d male partner and '. I18N::PLURAL .'%2$s has %1$d male partners and '=>'%2$s有%1$d名丈夫和',
            '%2$s has %1$d female partner and '. I18N::PLURAL .'%2$s has %1$d female partners and '=>'%2$s有%1$d名妻子和',
            '%d female partner recorded (%d in total).'. I18N::PLURAL .'%d female partners recorded (%d in total).'=>'%d位配偶（共%d位）',
            '%d male partner recorded (%d in total).'. I18N::PLURAL .'%d male partners recorded (%d in total).'=>'%d位配偶（共%d位）',
            '%d male partner of female partners recorded (%d in total).' . I18N::PLURAL . '%d male partners of female partners recorded (%d in total).'=> '%d位妻子的配偶(共%d位)',
            '%d female partner of male partners recorded (%d in total).' . I18N::PLURAL . '%d female partners of male partners recorded (%d in total).'=> '%d位丈夫的配偶(共%d位)',


            'Partner chains'=>'配偶系列',
            '%s has no members of a partner chain recorded.'=>'%s沒有記錄配偶鏈的成員。',
            'There are %d branches in the partner chain. '=>'配偶鏈中有%d位分支。',
            'The longest branch in the partner chain to %2$s consists of %1$d partners (including %3$s).'=>'%2$s配偶鏈中最長的分支由%1$d位配偶（包括%3$s）組成。',
            'The longest branch in the partner chain consists of %1$d partners (including %2$s).'=>'配偶鏈中最長的分支由%1$d位配偶（包括%2$s）組成。',
            '%d female partner in this partner chain recorded (%d in total). '. I18N::PLURAL .'%d female partners in this partner chain recorded (%d in total).'=>'%此配偶鏈中有d名女性配偶（%d總計）',

            'Cousins'=>'堂表親',
            '%s has no first cousins recorded.'=>'%s沒有表親記錄',
            '%s has one female first cousin recorded.'=>'%s有一位堂表姐妹的記錄。',
            '%s has one male first cousin recorded.'=>'%s有一位堂表兄弟的記錄。',
            '%s has one first cousin recorded.'=>'%s有一位堂表親的記錄。',
            '%2$s has %1$d female first cousin recorded.'. I18N::PLURAL .'%2$s has %1$d female first cousins recorded.'=>'%2$s有%1$d位堂表姐妹。',
            '%2$s has %1$d male first cousin recorded.'. I18N::PLURAL .'%2$s has %1$d male first cousins recorded.'=>'%2$s有%1$d位堂表兄弟',
            '%2$s has %1$d male first cousin and '. I18N::PLURAL .'%2$s has %1$d male first cousins and '=>'%2$s有%1$d位堂表兄弟和',
            '%d female first cousin recorded (%d in total).'. I18N::PLURAL .'%d female first cousins recorded (%d in total).'=>'%d位堂表姐妹（共%d位）。',


            'Nephews and Nieces'=>'侄子和侄女',
            '%s has no nephews or nieces recorded.'=>'%s沒有侄子或侄女的記錄。',
            '%s has one niece recorded.'=>'%s有一位侄女的記錄。',
            '%s has one nephew recorded.'=>'%s有一位侄子的記錄。',
            '%s has one nephew or niece recorded.'=>'%s有一位侄子或侄女的記錄。',
            '%2$s has %1$d niece recorded. '. I18N::PLURAL .'%2$s has %1$d nieces recorded.'=>'%2$s有%1$d位侄女',
            '%2$s has %1$d nephew recorded. '. I18N::PLURAL .'%2$s has %1$d nephews recorded.'=>'%2$s有%1$d位侄子',
            '%2$s has %1$d nephew and '. I18N::PLURAL .'%2$s has %1$d nephews and '=>'%2$s有%1$d位侄子和',
            '%d niece recorded (%d in total).'. I18N::PLURAL .'%d nieces recorded (%d in total).'=>'%d位侄女記錄（共%d位）',


            'Children'=>'子女',
            '%s has no children recorded.'=>'%s沒有子女的記錄。',
            '%s has one daughter recorded.'=>'%s有一個女兒。',
            '%s has one son recorded.'=>'%s有一個兒子的記錄。',
            '%s has one child recorded.'=>'%s有一個子女。',
            '%2$s has %1$d daughter recorded.'. I18N::PLURAL .'%2$s has %1$d daughters recorded.'=>'%2$s有%1$d個女兒',
            '%2$s has %1$d son recorded.'. I18N::PLURAL .'%2$s has %1$d sons recorded.'=>'%2$s有%1$d個兒子',
            '%2$s has %1$d son and '. I18N::PLURAL .'%2$s has %1$d sons and '=>'%2$s有%1$d個兒子和',
            '%d daughter recorded (%d in total).'. I18N::PLURAL .'%d daughters recorded (%d in total).'=>'%d個女兒（共%d位）。',


            'Children-in-law'=>'兒媳和女婿',
            '%s has no children-in-law recorded.'=>'%s沒有兒媳和女婿記錄。',
            '%s has one daughter-in-law recorded.'=>'%s有一個兒媳的記錄。',
            '%s has one son-in-law recorded.'=>'%s有一個女婿的記錄。',
            '%s has one child-in-law recorded.'=>'%s有一個兒媳或女婿的記錄。',
            '%2$s has %1$d daughter-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d daughters-in-law recorded.'=>'%2$s有%1$d位兒媳',
            '%2$s has %1$d son-in-law recorded.'. I18N::PLURAL .'%2$s has %1$d sons-in-law recorded.'=>'%2$s有%1$d位女婿記錄',
            '%2$s has %1$d son-in-law and '. I18N::PLURAL .'%2$s has %1$d sons-in-law and '=>'%2$s有%1$d位女婿和',
            '%d daughter-in-law recorded (%d in total).'. I18N::PLURAL .'%d daughters-in-law recorded (%d in total).'=>'%d位兒媳（共%d位）。',


            'Grandchildren'=>'孫輩',
            '%s has no grandchildren recorded.'=>'%s沒有孫輩的記錄。',
            '%s has one granddaughter recorded.'=>'%s有一個孫女。',
            '%s has one grandson recorded.'=>'%s有一個孫子。',
            '%s has one grandchild recorded.'=>'%s有一位孫輩的記錄。',
            '%2$s has %1$d granddaughter recorded.'. I18N::PLURAL .'%2$s has %1$d granddaughters recorded.'=>'%2$s有%1$d位孫女',
            '%2$s has %1$d grandson recorded.'. I18N::PLURAL .'%2$s has %1$d grandsons recorded.'=>'%2$s有%1$d位孫子',
            '%2$s has %1$d grandson and '. I18N::PLURAL .'%2$s has %1$d grandsons and '=>'%2$s有%1$d位孫子和',
            '%d granddaughter recorded (%d in total).'. I18N::PLURAL .'%d granddaughters recorded (%d in total).'=>'%d位孫女記錄（共%d位）',
            
            
            'Grandchildren-in-law' => '孫媳婦和孫女婿',
            '%s has no grandchildren-in-law recorded.' => '%s沒有孫媳婦和孫女婿的記錄。',
            '%s has one granddaughter-in-law recorded.' => '%s有一位孫媳婦',
            '%s has one grandson-in-law recorded.' => '%s有一位孫女婿',
            '%s has one grandchild-in-law of unknown sex recorded.' => '%s有一位孫輩的配偶',
            '%2$s has %1$d granddaughter-in-law recorded.' . I18N::PLURAL . '%2$s has %1$d granddaughters-in-law recorded.'
                => '%2$s有%1$d位孫媳婦',
            '%2$s has %1$d grandson-in-law recorded.' . I18N::PLURAL . '%2$s has %1$d grandsons-in-law recorded.'
                => '%2$s有%1$d位孫女婿',
            '%2$s has %1$d grandchild-in-law of unknown sex recorded.' . I18N::PLURAL . '%2$s has %1$d grandchildren-in-law of unknown sex recorded.'
                => '%s有%1$d位孫輩的配偶',
            '%2$s has %1$d grandson-in-law and ' . I18N::PLURAL . '%2$s has %1$d grandsons-in-law and '
                => '%2$s有%1$d位孫女婿和',
            '%d granddaughter-in-law recorded (%d in total).' . I18N::PLURAL . '%d granddaughters-in-law recorded (%d in total).'
                => '%d位孫媳婦（共%d位）',
            '%2$s has %1$d granddaughter-in-law and ' . I18N::PLURAL . '%2$s has %1$d granddaughters-in-law and '
                => '%2$s有%1$d位孫媳婦和',
            '%d grandchild-in-law of unknown sex recorded (%d in total).' . I18N::PLURAL . '%d grandchildren-in-law of unknown sex recorded (%d in total).'
                => '%d位孫輩的配偶（共%d位）。',
        ];
    }
